language: rust

before_install:
    - sudo apt-get install libsuitesparse-dev

matrix:
  include:
    - rust: nightly

script:
    - rustc --version
    - cargo --version
    - cargo test --all --verbose
    - cargo run --example heat

notifications:
  email:
    - on_success: change
    - on_failure: always

