[package]

name = "sprs"
description = "A sparse matrix library"
version = "0.7.1"
authors = ["Vincent Barrielle <vincent.barrielle@m4x.org>"]

readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vbarrielle/sprs"
documentation = "https://docs.rs/sprs"
keywords = ["sparse", "matrix", "linear", "algebra"]

exclude = [
    "data/*"
]

[features]
default = ["alga"]

[dependencies]
num-traits = "0.2.0"
ndarray = ">=0.11.0,<0.14"
alga = { version = "0.9.0", optional = true }
num-complex = "0.2.1"
serde = { version = "1.0.0", optional = true }
serde_derive = { version = "1.0.0", optional = true }
smallvec = "1.4.0"

[dev-dependencies]
bencher = "0.1.0"
tempdir = "0.3.5"
bincode = "1.2.0"
tobj = "2.0.0"
image = { version = "0.23.0", default-features = false, features = ["png"] }

[[bench]]
name = "suite"
harness = false

[[bench]]
name = "sparse_dense_products"
harness = false

[workspace]
members = [
    "sprs-ldl",
    "suitesparse_bindings/suitesparse_ldl_sys",
    "suitesparse_bindings/sprs_suitesparse_ldl",
    "sprs-rand",
    "sprs-benches",
]
