[package]
name = "sprs-rand"
version = "0.1.0"
authors = ["Vincent Barrielle <vincent.barrielle@m4x.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rand_distr = "0.2.2"
rand_pcg = "0.2.1"

[dependencies.sprs]
version = "0.7.1"
path = ".."
